### PR TITLE
dev update command updates homebrew itself

### PR DESCRIPTION
**Pull request by benjamin-smith**
I wanted to play with the latest versions of Docker & Docker Compose, and `dev update` wasn't pulling the latest.

### CODE REVIEW

**Comment by nettofarah** [comment]
This looks good to me.
@silvamerica?

**Comment by silvamerica** [comment]
I had this in originally, but it was taking a long time to do a Homebrew update during each `dev update`.

I'm not sure what the best option is, as automatically pulling in the latest each time _could_ cause problems. @benjamin-smith do you think that could be a problem?

**Comment by benjamin-smith** [comment]
I think there is value in having a distinction between updating Dash (a git pull) and updating related components (brew, ansible, docker, etc.) – the latter not needing to be run with each `update` execution. The latter could also be less desirable since it could affect workflows (we'd be subjected to the semver policy of each software package).

I've seen a lot of tools like this run the "git pull" update every X days with the opening of a new shell session. We'd need to add something to `.bashrc`/similar, but could be a good option (although not directly relevant to this discussion).

Thoughts? Happy to update the PR accordingly.

**Comment by silvamerica** [comment]
I don't think I'd want to run it automatically on shell invocation, but since this is an intentional command (and not run nearly as often as it was during development), I think it's okay.

**Pull request merged**
